### ISSUE TITLE
Possible misstatement in pillar 4 readme file

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-standards#31]
The second paragraph of the pillar 4 README says: _The NDA can be accessed here but link will only work if you work at DIME_.  The link can actually be accessed without having to log in to GH, so it seems to work for non-DIMErs as well

**Comment by luisesanmartin** [comment]
this is as of May 5 2021

**Comment by luisesanmartin** [comment]
maybe this is related somehow to #14?

**Comment by kbjarkefur** [comment]
Text updated. This was outdated following the move of the NDA back to the github repo
