### ISSUE TITLE
Typo in the first paragraph of dime-data-security-guidelines.md

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/dime-standards#8]
There is a typo in the second sentence of the first paragraph of the file `dime-data-security-guidelines.md`, which is repeated in the readme file of the folder `dime-standards/dime-research-standards/pillar-4-data-security/`. The text should be "To be fully compliant with the DIME Data Security Standards, a project **must** follow all applicable items" instead of "To be fully compliant with the DIME Data Security Standards, a project **most** follow all applicable items".

**Comment by kbjarkefur** [comment]
Fixed in 561c286. @luisesanmartin , when you have write access to this repo, please review and merge https://github.com/worldbank/dime-standards/pull/9
